---

# =============================================
# CONFIG
# =============================================

# site
root:
dest:             <%= site.root %>
data:             data

# assemble
templates:         site/templates
layouts:           <%= site.templates %>/layouts
layout:            default
pages:             <%= site.templates %>/pages
includes:          <%= site.templates %>/{includes, pages}
imgdir:            <%= site.root %>/img/site


# =============================================
# META
# =============================================

title:              DroidPinkman
author:             Dennis Gaebel
